### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by Devilscryer** [YanKlInnomme/FoundryVTT-k4lt#10]
Hi, 
love your System i have put a German Translation together with a Few People on the German Kult Discord.
would be great if you could add it :)
[de.txt](https://github.com/YanKlInnomme/FoundryVTT-k4lt/files/12417351/de.txt)

**Comment by YanKlInnomme** [comment]
![image](https://github.com/YanKlInnomme/FoundryVTT-k4lt/assets/100078854/440fd958-670d-4a64-8145-fab17a6198ac)

Thanks for the translation, it will be included in the next system update. I've attached a screenshot to give you a visual idea. However, the compendium of basic actions will not be translated. It's possible, but you'll have to use an add-on module, as I did for the French version (see the kult-fr module).
