### ISSUE TITLE
Dice so Nice

### ISSUE THREAD

**Issue by Devilscryer** [YanKlInnomme/FoundryVTT-k4lt#11]
I noticed if you roll a move all other Players won't see your 3D Dice

**Comment by Devilscryer** [comment]
have you had a chance to look into this? :) i found a topic an this with blades in the dark  https://github.com/megastruktur/foundryvtt-blades-in-the-dark/issues/98 i think its with this https://github.com/YanKlInnomme/FoundryVTT-k4lt/blob/master/modules/sheets/k4ltActor.js

**Comment by YanKlInnomme** [comment]
I read your previous message but I don't have the time to look at it in detail right now. As soon as I have time, I'll get to it.

**Comment by YanKlInnomme** [comment]
@Qaw J'ai regardé un peu et j'ai l'impression que cela demande pas mal de modifications, non ?
