### ISSUE TITLE
Lower Stability not affecting rolls for Disadvantages

### ISSUE THREAD

**Issue by Aaannndddrrreee** [YanKlInnomme/FoundryVTT-k4lt#14]
Lower Stability does not affect rolls for Disadvantages (like it does with See through the Illusion, or Keep it Together rolls when appropriate). Are there plans to correct it?

**Comment by YanKlInnomme** [comment]
Hello,
No, this wasn't planned, and for good reason. You're the first person to report this to me.
I've made the correction and you can update the system to version 2.1.4.1 to fix the problem.
