### ISSUE TITLE
Weapon Range Field

### ISSUE THREAD

**Issue by ericcberg** [YanKlInnomme/FoundryVTT-k4lt#20]
This needs to be a little bigger, to accommodate weapons with three usable ranges (like the Rifle).

**Comment by YanKlInnomme** [comment]
Thank you for your feedback. It has been taken into account for the 3.0.0.0 update.

**Comment by YanKlInnomme** [comment]
Thank you for your feedback. It has been taken into account for the 3.0.0.0 update.
