### ISSUE TITLE
Performance-heavy?

### ISSUE THREAD

**Issue by Mojo-89** [YanKlInnomme/FoundryVTT-k4lt#26]
System seems very performance-heavy.
I have a high-end computer and experience stutters when moving around windows.
Friends with cheaper laptops experience heavy lag when opening and moving windows. Almost unplayable.

Ideas:
Might it be due to unnecessarily large high-res texture files? Maybe a simple compression of the textures would fix it?

**Comment by YanKlInnomme** [comment]
Hello,

Thank you for your feedback and for taking the time to test the Kult: Divinity Lost game system.

I am surprised to hear that you and your friends are experiencing performance issues, as the Kult game system is relatively lightweight compared to other systems like Dungeons & Dragons 5th Edition. Here are some details about the size and optimization of the files:

- Total size of the game system: 8.43 MB
- Number of image files: 276
- Total size of image files: 6.82 MB
- Image format: webp (optimized for the web)

For comparison, the Dungeons & Dragons 5th Edition game system is 103.11 MB. This means that the Kult system is approximately **92% lighter** than the Dungeons & Dragons system.

I would like to understand more about where the issue might be coming from. Could you provide more details on the following points:

1. **Your computer's specifications and those of your friends:** Hardware specifications (CPU, RAM, GPU) and the operating system used.
2. **Version of Foundry VTT:** Which version of Foundry Virtual Tabletop are you using?
3. **Version of the Kult game system:** Which version of the Kult game system are you using?
4. **Usage context:** Do the slowdowns occur as soon as the system is opened or only after loading certain scenes or specific resources?
5. **Modules:** Are you using other modules with Foundry VTT that might interfere with the Kult system?
6. **Performance logs:** If possible, could you provide logs or screenshots of the performance (e.g., via the browser's developer tools F12) when the slowdowns occur?

Your detailed feedback will help us identify and fix the issue more effectively. Thank you in advance for your cooperation.

**Comment by Mojo-89** [comment]
That is odd indeed.
I looked at the webp-pictures in the assets-folder and they indeed are not high-res enough to cause a slowdown.

1. My PC specs: Ryzen 3900x, 32gb 3600mhz ram (corsair), RTX3080. Running on my 1440p monitor on windows 11 if that helps.
Let's ignore my friends potato-laptop for now. The laptop i 9 years old and I don't know if he was doing something simultaneously while using Kult.
2. Using the absolutely latest version of Foundry available as of now. V12 Build 328.
3. Using latest available Kult, from inside Foundry. 3.1.0.0 i believe.
4. Slowdown occurs when you open your character sheet and move it around or scroll within it. It's behaving like when moving around huge pictures in Photoshop for example. And the character sheet is pretty large. That's why I first thought high res textures (like those in the background of the char-sheet).
5. No mods at all.
6. Im not sure how to extract proper logs, but there are some errors shown when I press F12. I took a screenshot and copied the text into a .txt file.
![chrome_TL591zxKHb](https://github.com/user-attachments/assets/12e4a9da-6e6d-4498-b178-0ce7ff1a22a4) 
[Kult.txt](https://github.com/user-attachments/files/16262922/Kult.txt)

**Comment by YanKlInnomme** [comment]
The log does not contain any significant error (the select.options warning is just a depreciation indicator planned for future versions of Foundry VTT). So I have to say that I don't understand the problem at the moment. I'll see if I can get some feedback from other users. As far as I'm concerned, there's no problem, as you can see from this video:

https://github.com/user-attachments/assets/3c209be7-6884-46f6-ac27-852285248c31

And I don't have a brand-new computer:
Processor: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Physical memory: 32 GB
Video: NVIDIA GeForce GT 1030 (1920x1080x32b)
Operating system: Microsoft Windows 10 Professionnel

**Comment by Mojo-89** [comment]
I see some "delay" between your mouse pointer movement and character sheet window movement, when you move it back and forth. It is dragging behind. It seems to flow better on your computer though, for some reason.
This is not a huge deal but if you compare it to some other system, notice how the sheet window is much more "responsive".
It's not like I cannot use it, but something is making it slightly heavier than other systems.

Ah well, nothing is really broken and I have given my feedback.
Thank you for listening.

**Comment by YanKlInnomme** [comment]
I've got an idea if you'd like to test it. We're going to try a modification on the k4lt.css file located in the styles folder.

[k4lt.zip](https://github.com/user-attachments/files/16275754/k4lt.zip)

Can you replace the k4lt.css file with the one contained in this zip? I think that would help. Keep me posted and let me know what happens.

**Comment by Mojo-89** [comment]
Indeed it did help!
The window is super-responsive and feels great to work with now!
Nice job!

**Comment by YanKlInnomme** [comment]
I'm glad this temporary solution worked.

To solve the problem for good, I've done two things:

- I've optimized the SVG file (it's down from 1.76MB to 516kb)
- I've set up a low-resolution mode (accessible in the system options) that switches to the WEBP file if necessary.

These modifications will be included in system update 3.1.2.0.

**Comment by Mojo-89** [comment]
Wonderful work.
