### ISSUE TITLE
Problem adding Advantages/Disadvantajes/Relationships...

### ISSUE THREAD

**Issue by javierpm78** [YanKlInnomme/FoundryVTT-k4lt#3]
Thank you so much for your tought work! Look amazing!

However, or I don't know how to handle it or, it is not possible to add.

Any ideas?

![Screenshot_1](https://user-images.githubusercontent.com/128031011/225557182-cb976892-34b2-40a6-a9f0-48b0cfecd256.png)

**Comment by Qaw** [comment]
Drag 'n drop of the item on the sheet is not working ?

**Comment by YanKlInnomme** [comment]
You must go to the menu item
![Capture d’écran 2023-03-16 093240](https://user-images.githubusercontent.com/100078854/225560615-1d0c5122-a821-479e-9567-01295376c708.jpg)

And then create the desired elements
![Capture d’écran 2023-03-16 093327](https://user-images.githubusercontent.com/100078854/225560825-9fac7fd0-bc7f-48df-96e0-f3f53d90fd85.jpg)
![Capture d’écran 2023-03-16 093424](https://user-images.githubusercontent.com/100078854/225560852-85e88e98-641c-4790-a17f-d2bf2ebf6d6c.jpg)

Then on the character sheet
![Capture d’écran 2023-03-16 093443](https://user-images.githubusercontent.com/100078854/225561113-9913a07b-9ec7-4cba-b443-4ecbe96fa014.jpg)

Just drag and drop the elements directly on the form
![Capture d’écran 2023-03-16 093543](https://user-images.githubusercontent.com/100078854/225561411-57bc4429-1cfe-4cd4-8c12-dfe17e9db91b.jpg)

**Comment by javierpm78** [comment]
Thank you so much!! I just arrived here to say that I figured it out!! But thanks for taking your time on your reply!! I guess that it will be very helpful for newcomers!
