### ISSUE TITLE
[BUG] "undefined" à la place du nom des actions dans le journal

### ISSUE THREAD

**Issue by Dapoulp** [YanKlInnomme/FoundryVTT-k4lt#6]
J'ai un soucis lors du lancement d'une action, à la place du nom de l'action, c'est écrit "undefined".
J'ai testé avec et sans le module de traduction?
C'est assez bloquant du coup car on ne peut voir ce qui est lancé comme test

Une idée ?

**Comment by YanKlInnomme** [comment]
Bonjour est-ce que tu peux me faire une capture d'écran (ou même une vidéo) pour que je puisse localiser le souci.

Il me faudrait aussi le numéro de version du système installé et la liste des modules actifs.

**Comment by YanKlInnomme** [comment]
![image](https://user-images.githubusercontent.com/100078854/232988267-9a4b2afc-f8ed-41bb-a65d-e27540e245f6.png)

OK j'ai vu... Je regarde cela de suite.

**Comment by YanKlInnomme** [comment]
![image](https://user-images.githubusercontent.com/100078854/232991580-35f7b002-9b4e-43b8-8efb-4ff0fb40bf22.png)

**Comment by YanKlInnomme** [comment]
Merci @Dapoulp d'avoir signalé le problème. C'est corrigé avec la version 2.0.1.0 du système.
